server:
  port: 8080
#Credentials are defined per microservice
spring:
  datasource:
    schema: classpath*:db/mysql/schema.sql
    data: classpath*:db/mysql/data.sql
    platform: mysql
    initialization-mode: always
  cloud:
    services:
      registrationMethod: direct

management:
  metrics:
    export:
      wavefront:
        uri: ${vcap.services.TO-proxy.credentials.uri}
        api-token: ${vcap.services.TO-proxy.credentials.api-token}

wavefront:
  application:
    name: ${vcap.services.TO-proxy.credentials.application-name}
  freemium-account: false
